from qdrant_client import QdrantClient
from sentence_transformers import SentenceTransformer
from qdrant_client.models import VectorParams, Distance

from app.database import SessionLocal
from app.models import Product

COLLECTION_NAME = "products"
client = QdrantClient("localhost", port=6333, timeout = 60)

model = SentenceTransformer("all-MiniLM-L6-v2")

db= SessionLocal()

if not client.collection_exists("products"):

    client.create_collection (
        collection_name=COLLECTION_NAME,
        vectors_config = VectorParams(
            size=384, # this is the same size of embeddings generated by sentenc_transformers
            distance= Distance.COSINE
        )
    )

products = db.query(Product).all()

points= []

for p in products:
   if p.id>3:                     # to skip first 3 embeddings 
    text =  f"{p.name} {p.category} {p.use_case}"
    
    vector = model.encode(text)
    points.append ({
        "id": p.id,
        "vector": vector,
        "payload": {
            "product_id": p.id
        }
    })

    client.upsert(
        collection_name= "products",
        points = points
    )